<a href="https://colab.research.google.com/github/melgabay/Python/blob/main/_3_Array_calculations_and_operations_shecodes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercise #3: Array calculations and operations

###Aim: Use NumPy arrays in mathematical calculations

In this exercise we refers to a useful guide that can help you solve any questions in NumPy. This guide also summarize all that is needed to know about NumPy. [link to the guide](https://drive.google.com/file/d/0B9crmgoWupXkLTh0TS1HMzlrSVk/view)

###Issue covered:



*   Mathematical operations with arrays.
*   Mathematical operations mixing scalars and arrays.
*   Comparisons operators and Boolean operations on arrays.
*   Using the "where" method.
*   Mathematical operations on vectors.
*   Find coefficients and roots of polynomial.



First, import NumPy as np:







In [ ]:
import numpy as np




### 1.  Let’s perform some array calculations.
**Read “Array mathematics” (pages 8-10) and then:**





> (a) Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "a":








In [ ]:
# Your Code Here#
a = np.zeros((2,4) , int)
a[:1] = range(4)
a[1:2] = range(10,14)

print(a)

[[ 0  1  2  3]
 [10 11 12 13]]


> (b) Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "b" :


In [ ]:
# Your Code Here#
b = np.zeros((2,4), int )
b[:1] = range(4)
b[1:2] = range(10,14)

print(a)

[[ 0  1  2  3]
 [10 11 12 13]]



> (c) Multiply array "a" by "b" and view the results:




In [ ]:
# Your Code Here#
a = a*b
print(a)

[[  0   1   4   9]
 [100 121 144 169]]


Do you understand how NumPy has used its broadcasting feature to do the calculation even though the arrays are different shapes?



> (d) Multiply array "b" by 100 and assign the result to the variable "b1":



In [ ]:
# Your Code Here#
b1 = b*100

print(b1)

[[   0  100  200  300]
 [1000 1100 1200 1300]]




> (e) Multiply array "b" by 100.0 and assign the result to the variable "b2":



In [ ]:
# Your Code Here#
b2 = b*100.0

print(b2)

[[   0.  100.  200.  300.]
 [1000. 1100. 1200. 1300.]]




>(f) Print b1 == b2:





In [ ]:
# Your Code Here#
print(b1 == b2)

[[ True  True  True  True]
 [ True  True  True  True]]


Are they the same?



>(g) Why do they display differently? Interrogate the typecode of each array to find out why:



In [ ]:
# Your Code Here#
print(b1.dtype)
print(b2.dtype)


int64
float64


###2. Let's perform some operations on array.
Read the last code chunk on page 4 and read on until page 7 includes 
	Read “Basic array operations” (pages 11-12) and then:





> (a) Continue to use arrays "a" defined above:






> (b) Print the sum, mean and the product of "a" in two different ways:




In [ ]:
# Your Code Here#
print(a.sum())

sum=0
for x in a:
  for y in x:
    sum+=y
print(sum)


548
548




>(c) Print the variance and the standard deviation of "a"in two different ways:




In [ ]:
# Your Code Here#
print(np.var(a))

# calculate mean
m = a.sum() / a.size

# calculate variance using a list comprehension
var_res = sum((xi - m) ** 2 for xi in a) / a.size

4562.25


TypeError: ignored

###3. Let’s look at array comparisons.
Read “Comparisons operators and value testing” (pages 12-14). Then:





>(a)  Create an array of values 0 to 9 and assign it to the variable "arr":




In [ ]:
# Your Code Here#
arr = np.array(range(10))

print(arr)

[0 1 2 3 4 5 6 7 8 9]




>(b)  Print two different ways of expressing the condition where the array is less than 3:




In [ ]:
# Your Code Here#
for x in arr:
    if arr.item(x) < 3:
      print(arr.item(x))

print(arr<3)


0
1
2
[ True  True  True False False False False False False False]




>(c)  Create a numpy condition where "arr" is less than 3 OR greater than 8:




In [ ]:
# Your Code Here#

for x in arr:
  if arr.item(x)<3 or arr.item(x)>8:
          print(arr.item(x))


0
1
2
9




>(d)  Use the  *where*  function to create a new array where the value is arr * 5 if the above condition is True and arr * -5 where the condition is False:




In [ ]:
# Your Code Here#
new_arr = np.array
for x in arr:
  if arr.item(x)<3 or arr.item(x)>8:
    #item = arr.item(x)*5
    new_arr= np.insert (new_arr,x, (arr.item(x)*5))
    #np.append(new_arr, arr.item(x)*5)
  else :
    item = arr.item(x)*-5
    #np.append(new_arr, arr.item(x)*5)
    new_arr= np.insert(new_arr,x, (arr.item(x)*-5))

print(new_arr)  


[0 5 10 -15 -20 -25 -30 -35 -40 45 <built-in function array>]


###4. Let’s look at item selection and manipulation.
Read “Array item selection and manipulation” (pages 14-16).






>(a)  Continue to use arrays "a" defined above:






>(b)  Print an array contains all the values from "a" that are greater than 1:




In [ ]:
# Your Code Here#
print(a>1)  


[[False False  True  True]
 [ True  True  True  True]]




>(c)  Print an array contains all the values from "a" that are greater than 3 and smaller than 11:




In [ ]:
# Your Code Here#




>(d)  Create an array from the list range(6) and assign it to the variable "b":



In [ ]:
# Your Code Here#




>(e)  Use the  *put*  function to replace the first element of "b" with 6:




In [ ]:
# Your Code Here#




>(f)  Create an array from the list range(5) and assign it to the variable "c":




In [ ]:
# Your Code Here#




>(g)   Use the  *put*  function to replace the first element of "b" with the last element of "c":



In [ ]:
# Your Code Here#


## Goog Job!!